version: "3"

services:
  api_server:
    image: price-api:latest
    entrypoint: ["npm", "run", "start"]
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 4000:4000
